# When making changes to this file also update requirements.txt and pyproject.toml !!
# Usage:
# conda -v env update --file environment.yml; pre-commit run --all-files; pycheck

name: mausy5043-common

channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.12
  - pip
  # imported deps
  - numpy>=2.0.1
  - pandas==2.2.2
  - pyarrow==17.0.0

  # dev deps
  - pandas-stubs
  - pip
  - pipdeptree
  - pre-commit
