# When making changes to this file update requirements.txt also !!
# Usage: conda -v env update -n mausy5043-common --file environment.yml; pre-commit run --all-files

channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.11
  - numpy
  - pandas
  - pandas-stubs
  - pre-commit
  - pip
  # Not on conda channels:
  - pip:
      - pylint
